### ISSUE TITLE
Get undefined and crashed

### ISSUE THREAD

**Issue by WayneChang65** [WayneChang65/tosmm#143]
TypeError: Cannot read properties of undefined (reading 'split')
    at /usr/src/app/tosmm/lib/txt_react.js:78:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

TypeError: Cannot read properties of undefined (reading 'urls')
    at Object._pttCrawler [as pttCrawler] (/usr/src/app/tosmm/lib/crawler.js:67:43)
    at async Timeout._onTimeout (/usr/src/app/tosmm/lib/crawler_handler.js:26:13)

**Comment by WayneChang65** [comment]
#144
